version: "3"

services:

  web1:
    image: romeoz/docker-apache-php
    volumes:
      - ./www-data-1/:/var/www/app/:ro
      - ./config/flag1.txt:/flag.txt:ro
    working_dir: /var/www/app
    ports:
      - 8080:80
    depends_on:
      - backend.example.com

  backend.example.com:
    image: romeoz/docker-apache-php
    volumes:
      - ./config/flag2.txt:/var/www/app/index.php:ro
    working_dir: /var/www/app

  web2:
    image: romeoz/docker-apache-php
    volumes:
      - ./www-data-2/:/var/www/app/:ro
      - ./config/flag3.txt:/flag.txt:ro
    working_dir: /var/www/app
    ports:
      - 8081:80