version: "3"

services:

  web:
    image: romeoz/docker-apache-php
    volumes:
      - ./www/:/var/www/app/
      - ./config/dump.sql:/var/www/dump.sql:ro
    working_dir: /var/www/app
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:5.7.28
    volumes:
      - ./config/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'